import type { Aircraft, AudioFeed, FlockCamera, WebcamAsset } from "@/types/master-eye";
import { haversineMeters } from "@/lib/utils";

/** Deterministic offline seed used when PostGIS is unavailable */
export const FALLBACK_WEBCAMS: WebcamAsset[] = [
  {
    id: "cam-nyc-1",
    ip: "185.199.108.153",
    port: 80,
    product: "webcamxp",
    title: "NYC Midtown Traffic Cam",
    city: "New York",
    country: "United States",
    countryCode: "US",
    latitude: 40.758,
    longitude: -73.9855,
    snapshotUrl: "https://picsum.photos/seed/nyc1/640/360",
    streamUrl: "https://picsum.photos/seed/nyc1/1280/720",
    protocol: "http",
    tags: ["traffic", "urban"],
    isActive: true,
  },
  {
    id: "cam-jfk-1",
    ip: "104.18.32.7",
    port: 80,
    product: "mjpeg",
    title: "JFK Runway 31L Overlay",
    city: "New York",
    country: "United States",
    countryCode: "US",
    latitude: 40.6413,
    longitude: -73.7781,
    snapshotUrl: "https://picsum.photos/seed/jfk1/640/360",
    streamUrl: "https://picsum.photos/seed/jfk1/1280/720",
    protocol: "http",
    tags: ["airport", "aviation"],
    isActive: true,
  },
  {
    id: "cam-lax-1",
    ip: "104.21.16.1",
    port: 8080,
    product: "mjpeg",
    title: "LAX Approach Corridor Cam",
    city: "Los Angeles",
    country: "United States",
    countryCode: "US",
    latitude: 33.9425,
    longitude: -118.4081,
    snapshotUrl: "https://picsum.photos/seed/lax1/640/360",
    streamUrl: "https://picsum.photos/seed/lax1/1280/720",
    protocol: "http",
    tags: ["airport", "aviation"],
    isActive: true,
  },
  {
    id: "cam-chi-1",
    ip: "151.101.1.69",
    port: 80,
    product: "axis",
    title: "Chicago Loop Skyline",
    city: "Chicago",
    country: "United States",
    countryCode: "US",
    latitude: 41.8781,
    longitude: -87.6298,
    snapshotUrl: "https://picsum.photos/seed/chi1/640/360",
    streamUrl: "https://picsum.photos/seed/chi1/1280/720",
    protocol: "http",
    tags: ["skyline"],
    isActive: true,
  },
  {
    id: "cam-lhr-1",
    ip: "93.184.216.34",
    port: 554,
    product: "rtsp",
    title: "Heathrow Perimeter View",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    latitude: 51.47,
    longitude: -0.4543,
    snapshotUrl: "https://picsum.photos/seed/lhr1/640/360",
    streamUrl: "https://picsum.photos/seed/lhr1/1280/720",
    protocol: "rtsp",
    tags: ["airport"],
    isActive: true,
  },
  {
    id: "cam-tyo-1",
    ip: "142.250.185.78",
    port: 80,
    product: "webcamxp",
    title: "Tokyo Bay Harbor Cam",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    latitude: 35.6528,
    longitude: 139.8395,
    snapshotUrl: "https://picsum.photos/seed/tyo1/640/360",
    streamUrl: "https://picsum.photos/seed/tyo1/1280/720",
    protocol: "http",
    tags: ["harbor", "maritime"],
    isActive: true,
  },
  {
    id: "cam-sfo-1",
    ip: "151.101.65.69",
    port: 8081,
    product: "foscam",
    title: "SFO Bay Bridge Cam",
    city: "San Francisco",
    country: "United States",
    countryCode: "US",
    latitude: 37.8199,
    longitude: -122.4783,
    snapshotUrl: "https://picsum.photos/seed/sfo1/640/360",
    streamUrl: "https://picsum.photos/seed/sfo1/1280/720",
    protocol: "http",
    tags: ["bridge", "traffic"],
    isActive: true,
  },
  {
    id: "cam-dxb-1",
    ip: "104.16.132.229",
    port: 80,
    product: "hikvision",
    title: "Dubai Marina Waterfront",
    city: "Dubai",
    country: "United Arab Emirates",
    countryCode: "AE",
    latitude: 25.0805,
    longitude: 55.1403,
    snapshotUrl: "https://picsum.photos/seed/dxb1/640/360",
    streamUrl: "https://picsum.photos/seed/dxb1/1280/720",
    protocol: "http",
    tags: ["marina"],
    isActive: true,
  },
  {
    id: "cam-syd-1",
    ip: "13.32.92.10",
    port: 80,
    product: "dlink",
    title: "Sydney Harbour Lookout",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    latitude: -33.8568,
    longitude: 151.2153,
    snapshotUrl: "https://picsum.photos/seed/syd1/640/360",
    streamUrl: "https://picsum.photos/seed/syd1/1280/720",
    protocol: "http",
    tags: ["harbour"],
    isActive: true,
  },
  {
    id: "cam-mia-1",
    ip: "23.227.38.65",
    port: 8080,
    product: "webcamxp",
    title: "Miami Beach Pier Cam",
    city: "Miami",
    country: "United States",
    countryCode: "US",
    latitude: 25.7907,
    longitude: -80.13,
    snapshotUrl: "https://picsum.photos/seed/mia1/640/360",
    streamUrl: "https://picsum.photos/seed/mia1/1280/720",
    protocol: "http",
    tags: ["beach"],
    isActive: true,
  },
  {
    id: "cam-ber-1",
    ip: "151.101.193.69",
    port: 80,
    product: "axis",
    title: "Berlin Brandenburg Gate Area",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    latitude: 52.5163,
    longitude: 13.3777,
    snapshotUrl: "https://picsum.photos/seed/ber1/640/360",
    streamUrl: "https://picsum.photos/seed/ber1/1280/720",
    protocol: "http",
    tags: ["landmark"],
    isActive: true,
  },
  {
    id: "cam-cdg-1",
    ip: "192.0.66.2",
    port: 8080,
    product: "webcamxp",
    title: "Paris CDG Terminal Approach",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    latitude: 49.0097,
    longitude: 2.5479,
    snapshotUrl: "https://picsum.photos/seed/cdg1/640/360",
    streamUrl: "https://picsum.photos/seed/cdg1/1280/720",
    protocol: "http",
    tags: ["airport"],
    isActive: true,
  },
];

export const FALLBACK_AUDIO: AudioFeed[] = [
  {
    id: "audio-kjfk-twr",
    name: "KJFK Tower",
    feedType: "aviation",
    description: "John F. Kennedy International — Tower",
    city: "New York",
    region: "NY",
    country: "United States",
    countryCode: "US",
    latitude: 40.6413,
    longitude: -73.7781,
    streamUrl: "https://s1-fmt2.liveatc.net/kjfk_twr",
    websiteUrl: "https://www.liveatc.net/search/?icao=KJFK",
    frequency: "119.100",
    isActive: true,
  },
  {
    id: "audio-kjfk-app",
    name: "KJFK Approach",
    feedType: "aviation",
    description: "JFK Approach Control",
    city: "New York",
    region: "NY",
    country: "United States",
    countryCode: "US",
    latitude: 40.65,
    longitude: -73.79,
    streamUrl: "https://s1-fmt2.liveatc.net/kjfk_app",
    websiteUrl: "https://www.liveatc.net/search/?icao=KJFK",
    frequency: "125.700",
    isActive: true,
  },
  {
    id: "audio-klax-twr",
    name: "KLAX Tower",
    feedType: "aviation",
    description: "Los Angeles International — Tower",
    city: "Los Angeles",
    region: "CA",
    country: "United States",
    countryCode: "US",
    latitude: 33.9425,
    longitude: -118.4081,
    streamUrl: "https://s1-fmt2.liveatc.net/klax_twr",
    websiteUrl: "https://www.liveatc.net/search/?icao=KLAX",
    frequency: "133.900",
    isActive: true,
  },
  {
    id: "audio-egll-twr",
    name: "EGLL Heathrow Tower",
    feedType: "aviation",
    description: "London Heathrow — Tower",
    city: "London",
    region: "ENG",
    country: "United Kingdom",
    countryCode: "GB",
    latitude: 51.47,
    longitude: -0.4543,
    streamUrl: "https://s1-fmt2.liveatc.net/egll_twr",
    websiteUrl: "https://www.liveatc.net/search/?icao=EGLL",
    frequency: "118.700",
    isActive: true,
  },
  {
    id: "audio-ksfo-twr",
    name: "KSFO Tower",
    feedType: "aviation",
    description: "San Francisco International — Tower",
    city: "San Francisco",
    region: "CA",
    country: "United States",
    countryCode: "US",
    latitude: 37.6213,
    longitude: -122.379,
    streamUrl: "https://s1-fmt2.liveatc.net/ksfo_twr",
    websiteUrl: "https://www.liveatc.net/search/?icao=KSFO",
    frequency: "120.500",
    isActive: true,
  },
  {
    id: "audio-nyc-pd",
    name: "NYC Metro Police Scanner",
    feedType: "police",
    description: "New York City metro dispatch relay",
    city: "New York",
    region: "NY",
    country: "United States",
    countryCode: "US",
    latitude: 40.7128,
    longitude: -74.006,
    streamUrl: "https://broadcastify.cdnstream1.com/1225",
    websiteUrl: "https://www.broadcastify.com",
    frequency: "460.025",
    isActive: true,
  },
  {
    id: "audio-la-fire",
    name: "LA County Fire Dispatch",
    feedType: "fire",
    description: "Los Angeles County Fire mutual aid",
    city: "Los Angeles",
    region: "CA",
    country: "United States",
    countryCode: "US",
    latitude: 34.0522,
    longitude: -118.2437,
    streamUrl: "https://broadcastify.cdnstream1.com/18699",
    websiteUrl: "https://www.broadcastify.com",
    frequency: "154.190",
    isActive: true,
  },
  {
    id: "audio-chi-pd",
    name: "Chicago PD Zone 1",
    feedType: "police",
    description: "Chicago Police Zone 1 scanner",
    city: "Chicago",
    region: "IL",
    country: "United States",
    countryCode: "US",
    latitude: 41.8781,
    longitude: -87.6298,
    streamUrl: "https://broadcastify.cdnstream1.com/14791",
    websiteUrl: "https://www.broadcastify.com",
    frequency: "460.500",
    isActive: true,
  },
  {
    id: "audio-rjtt",
    name: "RJTT Tokyo Tower",
    feedType: "aviation",
    description: "Tokyo Haneda — Tower",
    city: "Tokyo",
    region: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    latitude: 35.5494,
    longitude: 139.7798,
    streamUrl: "https://s1-fmt2.liveatc.net/rjtt_twr",
    websiteUrl: "https://www.liveatc.net/search/?icao=RJTT",
    frequency: "118.100",
    isActive: true,
  },
  {
    id: "audio-eddb",
    name: "EDDB Berlin Tower",
    feedType: "aviation",
    description: "Berlin Brandenburg — Tower",
    city: "Berlin",
    region: "BE",
    country: "Germany",
    countryCode: "DE",
    latitude: 52.3667,
    longitude: 13.5033,
    streamUrl: "https://s1-fmt2.liveatc.net/eddb_twr",
    websiteUrl: "https://www.liveatc.net/search/?icao=EDDB",
    frequency: "118.400",
    isActive: true,
  },
  {
    id: "audio-mia-em",
    name: "Miami-Dade Emergency",
    feedType: "emergency",
    description: "Miami-Dade County emergency ops",
    city: "Miami",
    region: "FL",
    country: "United States",
    countryCode: "US",
    latitude: 25.7617,
    longitude: -80.1918,
    streamUrl: "https://broadcastify.cdnstream1.com/18111",
    websiteUrl: "https://www.broadcastify.com",
    frequency: "154.280",
    isActive: true,
  },
  {
    id: "audio-lfpg",
    name: "LFPG CDG Tower",
    feedType: "aviation",
    description: "Paris Charles de Gaulle — Tower",
    city: "Paris",
    region: "IDF",
    country: "France",
    countryCode: "FR",
    latitude: 49.0097,
    longitude: 2.5479,
    streamUrl: "https://s1-fmt2.liveatc.net/lfpg_twr",
    websiteUrl: "https://www.liveatc.net/search/?icao=LFPG",
    frequency: "119.250",
    isActive: true,
  },
];

/** Seeded Flock / ALPR nodes (demo when Overpass/PostGIS unavailable) */
export const FALLBACK_FLOCK: FlockCamera[] = [
  {
    id: "flock-nyc-1",
    osmId: "seed-nyc-1",
    name: "Flock Falcon — Midtown E 42nd",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "NYPD partner network",
    city: "New York",
    state: "NY",
    country: "United States",
    countryCode: "US",
    latitude: 40.7516,
    longitude: -73.9755,
    direction: 270,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr", "falcon"],
    isActive: true,
  },
  {
    id: "flock-nyc-2",
    osmId: "seed-nyc-2",
    name: "Flock Falcon — FDR Drive / 34th",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "NYPD partner network",
    city: "New York",
    state: "NY",
    country: "United States",
    countryCode: "US",
    latitude: 40.7441,
    longitude: -73.9721,
    direction: 180,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr"],
    isActive: true,
  },
  {
    id: "flock-nyc-3",
    osmId: null,
    name: "Flock Falcon — Brooklyn Bridge approach",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "NYPD partner network",
    city: "New York",
    state: "NY",
    country: "United States",
    countryCode: "US",
    latitude: 40.7061,
    longitude: -73.9969,
    direction: 45,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr", "bridge"],
    isActive: true,
  },
  {
    id: "flock-jfk-1",
    osmId: "seed-jfk-1",
    name: "Flock Falcon — JFK Van Wyck corridor",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "Port Authority / LE",
    city: "Queens",
    state: "NY",
    country: "United States",
    countryCode: "US",
    latitude: 40.6586,
    longitude: -73.7956,
    direction: 0,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr", "airport"],
    isActive: true,
  },
  {
    id: "flock-lax-1",
    osmId: "seed-lax-1",
    name: "Flock Falcon — Century Blvd / LAX",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "LAPD partner network",
    city: "Los Angeles",
    state: "CA",
    country: "United States",
    countryCode: "US",
    latitude: 33.9456,
    longitude: -118.3947,
    direction: 90,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr", "airport"],
    isActive: true,
  },
  {
    id: "flock-chi-1",
    osmId: "seed-chi-1",
    name: "Flock Falcon — Loop Wacker Dr",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "CPD partner network",
    city: "Chicago",
    state: "IL",
    country: "United States",
    countryCode: "US",
    latitude: 41.8865,
    longitude: -87.6368,
    direction: 180,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr"],
    isActive: true,
  },
  {
    id: "flock-atl-1",
    osmId: null,
    name: "Flock Falcon — Downtown Peachtree",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "APD partner network",
    city: "Atlanta",
    state: "GA",
    country: "United States",
    countryCode: "US",
    latitude: 33.759,
    longitude: -84.388,
    direction: 0,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr"],
    isActive: true,
  },
  {
    id: "flock-hou-1",
    osmId: null,
    name: "Flock Falcon — Downtown Houston",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "HPD partner network",
    city: "Houston",
    state: "TX",
    country: "United States",
    countryCode: "US",
    latitude: 29.7604,
    longitude: -95.3698,
    direction: 270,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr"],
    isActive: true,
  },
  {
    id: "flock-phx-1",
    osmId: null,
    name: "Flock Falcon — Central Ave corridor",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "Phoenix PD partner",
    city: "Phoenix",
    state: "AZ",
    country: "United States",
    countryCode: "US",
    latitude: 33.4484,
    longitude: -112.074,
    direction: 180,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr"],
    isActive: true,
  },
  {
    id: "flock-mia-1",
    osmId: null,
    name: "Flock Falcon — Brickell Ave",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "Miami PD partner",
    city: "Miami",
    state: "FL",
    country: "United States",
    countryCode: "US",
    latitude: 25.7617,
    longitude: -80.1918,
    direction: 90,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr"],
    isActive: true,
  },
  {
    id: "flock-den-1",
    osmId: null,
    name: "Flock Falcon — Colfax corridor",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "DPD partner network",
    city: "Denver",
    state: "CO",
    country: "United States",
    countryCode: "US",
    latitude: 39.7392,
    longitude: -104.9903,
    direction: 90,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr"],
    isActive: true,
  },
  {
    id: "flock-sea-1",
    osmId: null,
    name: "Flock Falcon — SODO corridor",
    manufacturer: "Flock Safety",
    model: "Falcon",
    operator: "SPD partner network",
    city: "Seattle",
    state: "WA",
    country: "United States",
    countryCode: "US",
    latitude: 47.5805,
    longitude: -122.3331,
    direction: 0,
    surveillanceType: "ALPR",
    source: "seed",
    tags: ["flock", "alpr"],
    isActive: true,
  },
];

export function filterByRadius<T extends { latitude: number; longitude: number }>(
  items: T[],
  lat: number,
  lon: number,
  radiusMeters: number
): (T & { distanceM: number })[] {
  return items
    .map((item) => ({
      ...item,
      distanceM: haversineMeters(lat, lon, item.latitude, item.longitude),
    }))
    .filter((item) => item.distanceM <= radiusMeters)
    .sort((a, b) => a.distanceM - b.distanceM);
}

/** Synthetic aircraft when OpenSky is rate-limited or unreachable */
export function generateDemoAircraft(
  lat: number,
  lon: number,
  count = 12
): Aircraft[] {
  const callsigns = [
    "UAL442",
    "DAL218",
    "AAL100",
    "SWA1847",
    "BAW178",
    "AFR007",
    "JBU624",
    "EZY8821",
    "QTR37A",
    "ANA216",
    "FDX1203",
    "N17MX",
  ];
  const now = Math.floor(Date.now() / 1000);
  return Array.from({ length: count }, (_, i) => {
    const angle = (i / count) * Math.PI * 2;
    const dist = 0.05 + (i % 5) * 0.04;
    return {
      icao24: `a${(100000 + i * 137).toString(16).slice(0, 5)}`,
      callsign: callsigns[i % callsigns.length],
      originCountry: "United States",
      latitude: lat + Math.sin(angle) * dist,
      longitude: lon + Math.cos(angle) * dist,
      altitudeM: 3000 + (i % 8) * 1200,
      velocityMs: 120 + (i % 6) * 25,
      heading: (angle * 180) / Math.PI,
      verticalRate: i % 3 === 0 ? -2.5 : i % 3 === 1 ? 1.8 : 0,
      squawk: i % 4 === 0 ? "7700" : "1200",
      onGround: false,
      lastContact: now,
    };
  });
}
